# Assignment 6 

###  QUESTION 1:  Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [46]:
x = np.array([1, 2, 3])
N = 3
np.vander(x, increasing = False)

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

In [45]:
x = np.array([1, 2, 3])
N = 3
np.vander(x, increasing = True)

array([[1, 1, 1],
       [1, 2, 4],
       [1, 3, 9]])

### QUESTION 2:   Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [55]:
x=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
x

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])