# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [1]:
import numpy as np

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [90]:
mat1 = np.arange(0,9).reshape(3,3)
mat2 = np.arange(10,19).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1 + mat2)
print("\nMultiplication\n------------------\n", mat1*3)

print("\nExponentiation, matrix cubed here\n----------------------------------------\n", np.power(mat1,3))



1st Matrix of random single-digit numbers
----------------------------------------
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[10 11 12]
 [13 14 15]
 [16 17 18]]

Addition
------------------
 [[10 12 14]
 [16 18 20]
 [22 24 26]]

Multiplication
------------------
 [[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]

Exponentiation, matrix cubed here
----------------------------------------
 [[  0   1   8]
 [ 27  64 125]
 [216 343 512]]


Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [86]:
from numpy.random import randint as ri
mat1 = np.random.randint(50, size=(3,3))
mat2 = np.random.randint(50, size=(3,3))
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",mat1.sum(axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",mat1.sum(axis=1))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",mat1.mean())


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",mat1.std())


mat1 =  np.random.randint(99, size=(3,3))
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",mat1.std())


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",mat1.var())


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[45  0 33]
 [44 14 43]
 [40 27 11]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[ 9 18 13]
 [22 40 30]
 [16 31 37]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 257

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [129  41  87]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [ 78 101  78]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 28.555555555555557

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 15.656813292274254

Modified matrix of random numbers from 1 to 99
 -------------------------------------------------- 
 [[96 65 33]
 [69 46 97]
 [64 24 20]]

Standard deviation of all numbers in the modifi

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [46]:
##Solution
A=np.arange(2, 11).reshape(3,3)
A

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [47]:
A.reshape(9,1)

array([[ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

### 4.Sort

In [61]:
A = np.random.randint(0,101,10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [94 11 39 87 84 61 59 10 21 74]

Here is the sorted vector
 -------------------------------------------------- 
 [10 11 21 39 59 61 74 84 87 94]


In [73]:
M = np.random.randint(25, size=(5,5)) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,axis=1)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[14 17  9  4 20]
 [23 19 11 15 16]
 [ 6 15 24  4  2]
 [12 11 10  7 21]
 [12  2  4  7 12]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[ 4  9 14 17 20]
 [11 15 16 19 23]
 [ 2  4  6 15 24]
 [ 7 10 11 12 21]
 [ 2  4  7 12 12]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 6  2  4  4  2]
 [12 11  9  4 12]
 [12 15 10  7 16]
 [14 17 11  7 20]
 [23 19 24 15 21]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [102]:
# Fill the following ***** with appropriate solution.
a=np.random.randint(10,size=(1,10))
b=np.random.randint(20, size=(1,10))
c=np.random.randint(20, size=(1,10))

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", np.amax(a))
print("Max of b:",np.amax(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))

print("Max of a:", np.amax(a))
print("Max of b:", np.amax(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))



a: [[2 1 4 0 0 5 1 5 2 4]]
b: [[19  5 14 16 15  0  1  1  0  5]]
c: [[15 17  2  7  1  7 11  2 16 16]]
Max of a: 5
Max of b: 19
Max of a location: 5
Max of b location: 0
Max of c location: 1
Max of a: 5
Max of b: 19
Max of a location: 5
Max of b location: 0
Max of c location: 1


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [113]:

mat1 = np.random.randint(9, size=(3,3))
mat2 = np.random.randint(9, size=(3,3))
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.mod(mat1,mat2))



1st Matrix of random single-digit numbers
----------------------------------------
 [[5 5 2]
 [5 5 5]
 [3 1 2]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[8 5 6]
 [7 7 4]
 [8 8 6]]

Sq-root of 1st matrix using np
------------------
 [[2.23606798 2.23606798 1.41421356]
 [2.23606798 2.23606798 2.23606798]
 [1.73205081 1.         1.41421356]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[148.4131591  148.4131591    7.3890561 ]
 [148.4131591  148.4131591  148.4131591 ]
 [ 20.08553692   2.71828183   7.3890561 ]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.69897    0.69897    0.30103   ]
 [0.69897    0.69897    0.69897   ]
 [0.47712125 0.         0.30103   ]]

Modulo reminder using np
 -------------------------------------------------- 
 [[5 0 2]
 [5 5 1]
 [3 1 2]]


### 7.Generating matrices from distributions

In [114]:

print("Random number generation (from Uniform distribution)")
print(np.random.randint(1, size=(2,3))) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(******)

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(********) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",*******) # 20 samples drawn from a dice throw

SyntaxError: invalid syntax (<ipython-input-114-1e06a80e2839>, line 6)

### 8.Find the nearest value from a given number in an array using NumPy.

In [21]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element

4.859577122593637


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]